// layout.tsx (Server Component)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientLayout } from "./ClientLayout";
import { TheoLogo } from "@/components/Theo";
import HideNavIfNotSignedIn from "@/hooks/use-check-user-signed-in";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-theme-background text-slate-100`}
      >
        <ClientLayout>
          <div className="w-full">
            <HideNavIfNotSignedIn>
              <nav className="flex justify-between items-center p-4">
                <div className="flex gap-2 items-center">
                  <TheoLogo />
                </div>
              </nav>
            </HideNavIfNotSignedIn>
            {children}
          </div>
        </ClientLayout>
      </body>
    </html>
  );
}
